%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/icey/Desktop/project/camera_localization/data/mav0/cam0/data

# camera intrinsics
# fr1
camera.fx: 458.654
camera.fy: 457.296
camera.cx: 367.215
camera.cy: 248.375
distortion_coefficients: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

camera.depth_scale: 5000

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 10
min_inliers: 30
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1
